version: "3"
services:
  app:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: cms-upload-images
    environment:
      - NODE_ENV=development
