version: "3"
services:
  app:
    build: .
    ports:
      - "9098:9000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /home/saintent/cms_app/image/shop/:/usr/src/app/uploads/
    container_name: cms-upload-images
    environment:
      - NODE_ENV=development
